language: python
python:
 - "3.6"
services:
 - docker
before_install:
 - docker pull yagudinamir/cv
script:
 - docker run -v `pwd`:/tmp -ti yagudinamir/cv /bin/bash -c "source activate test_x; jupyter nbconvert --to html /tmp/notebooks/day1/seminar_image_processing_intro.ipynb"
